name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Trigger event name: ${{ github.event.name }}"
          echo "Branch name: ${{ github.ref }}"
      
      - uses: actions/checkout@v3.3.0
      
      - name: List all files
        run: |
          echo "The repository ${{ github.repository }} contains the following:"
          tree
